/********************************************************************
* sbsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error sbsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablesbsDict();
extern void G__cpp_setup_inheritancesbsDict();
extern void G__cpp_setup_typetablesbsDict();
extern void G__cpp_setup_memvarsbsDict();
extern void G__cpp_setup_globalsbsDict();
extern void G__cpp_setup_memfuncsbsDict();
extern void G__cpp_setup_funcsbsDict();
extern void G__set_cpp_environmentsbsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MPDModule.h"
#include "SBSBigBite.h"
#include "SBSGEMStand.h"
#include "SBSGEMPlane.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__sbsDictLN_TClass;
extern G__linked_taginfo G__sbsDictLN_TBuffer;
extern G__linked_taginfo G__sbsDictLN_TMemberInspector;
extern G__linked_taginfo G__sbsDictLN_TObject;
extern G__linked_taginfo G__sbsDictLN_TNamed;
extern G__linked_taginfo G__sbsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__sbsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__sbsDictLN_TClonesArray;
extern G__linked_taginfo G__sbsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__sbsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__sbsDictLN_Decoder;
extern G__linked_taginfo G__sbsDictLN_DecodercLcLModule;
extern G__linked_taginfo G__sbsDictLN_DecodercLcLVmeModule;
extern G__linked_taginfo G__sbsDictLN_DecodercLcLTHaSlotData;
extern G__linked_taginfo G__sbsDictLN_DecodercLcLEModuleType;
extern G__linked_taginfo G__sbsDictLN_setlEDecodercLcLModulecLcLModuleTypecOlesslEDecodercLcLModulecLcLModuleTypegRcOallocatorlEDecodercLcLModulecLcLModuleTypegRsPgR;
extern G__linked_taginfo G__sbsDictLN_setlEDecodercLcLModulecLcLModuleTypecOlesslEDecodercLcLModulecLcLModuleTypegRcOallocatorlEDecodercLcLModulecLcLModuleTypegRsPgRcLcLiterator;
extern G__linked_taginfo G__sbsDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__sbsDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__sbsDictLN_DecodercLcLMPDModule;
extern G__linked_taginfo G__sbsDictLN_THaRunBase;
extern G__linked_taginfo G__sbsDictLN_TDatime;
extern G__linked_taginfo G__sbsDictLN_THaEvData;
extern G__linked_taginfo G__sbsDictLN_THaAnalysisObject;
extern G__linked_taginfo G__sbsDictLN_THaAnalysisObjectcLcLEStatus;
extern G__linked_taginfo G__sbsDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__sbsDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__sbsDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__sbsDictLN_THaDetector;
extern G__linked_taginfo G__sbsDictLN_THaApparatus;
extern G__linked_taginfo G__sbsDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__sbsDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__sbsDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__sbsDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__sbsDictLN_THaVertexModule;
extern G__linked_taginfo G__sbsDictLN_THaSpectrometer;
extern G__linked_taginfo G__sbsDictLN_THaTrackingModule;
extern G__linked_taginfo G__sbsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__sbsDictLN_THaDetectorBase;
extern G__linked_taginfo G__sbsDictLN_THaSpectrometerDetector;
extern G__linked_taginfo G__sbsDictLN_SBSBigBite;
extern G__linked_taginfo G__sbsDictLN_THaTrackingDetector;
extern G__linked_taginfo G__sbsDictLN_SBSGEMPlane;
extern G__linked_taginfo G__sbsDictLN_THaCrateMap;
extern G__linked_taginfo G__sbsDictLN_SBSGEMStand;
extern G__linked_taginfo G__sbsDictLN_vectorlESBSGEMPlanemUcOallocatorlESBSGEMPlanemUgRsPgR;
extern G__linked_taginfo G__sbsDictLN_reverse_iteratorlEvectorlESBSGEMPlanemUcOallocatorlESBSGEMPlanemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__sbsDictLN_THaSubDetector;
extern G__linked_taginfo G__sbsDictLN_vectorlEmpdmap_tcOallocatorlEmpdmap_tgRsPgR;
extern G__linked_taginfo G__sbsDictLN_reverse_iteratorlEvectorlEmpdmap_tcOallocatorlEmpdmap_tgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
